using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Zooper.Tools.Marten.ApplyEnforcer.Analyzers;

[Generator(LanguageNames.CSharp)]
public sealed class EventSourcedProjectionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var projections = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is TypeDeclarationSyntax declaration && declaration.AttributeLists.Count > 0,
                static (ctx, _) => GetProjectionCandidate(ctx))
            .Where(static candidate => candidate is not null)
            .Select(static (candidate, _) => candidate!);

        var events = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is TypeDeclarationSyntax,
                static (ctx, _) => GetAggregateEventCandidate(ctx))
            .Where(static candidate => candidate is not null)
            .Select(static (candidate, _) => candidate!);

        context.RegisterSourceOutput(projections.Collect().Combine(events.Collect()), static (productionContext, source) =>
        {
            var projectionMap = new Dictionary<string, ProjectionCandidate>();

            foreach (var projection in source.Left)
            {
                projectionMap[projection.HostType.ToDisplayString()] = projection;
            }

            var eventsByAggregate = new Dictionary<string, List<INamedTypeSymbol>>();

            foreach (var aggregateEvent in source.Right)
            {
                foreach (var aggregateType in aggregateEvent.AggregateTypes)
                {
                    var aggregateKey = aggregateType.ToDisplayString();
                    if (!eventsByAggregate.TryGetValue(aggregateKey, out var bucket))
                    {
                        bucket = [];
                        eventsByAggregate[aggregateKey] = bucket;
                    }

                    if (!bucket.Any(existing => SymbolEqualityComparer.Default.Equals(existing, aggregateEvent.EventType)))
                    {
                        bucket.Add(aggregateEvent.EventType);
                    }
                }
            }

            foreach (var projection in projectionMap.Values.OrderBy(candidate => candidate.HostType.ToDisplayString()))
            {
                eventsByAggregate.TryGetValue(projection.AggregateType.ToDisplayString(), out var aggregateEvents);
                EmitCoverageSource(productionContext, projection, aggregateEvents ?? []);
            }
        });
    }

    private static ProjectionCandidate? GetProjectionCandidate(GeneratorSyntaxContext context)
    {
        if (context.Node is not TypeDeclarationSyntax declaration)
        {
            return null;
        }

        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        return SymbolHelpers.TryGetProjectionAggregate(symbol, out var aggregateType)
            ? new ProjectionCandidate(symbol, aggregateType!)
            : null;
    }

    private static AggregateEventCandidate? GetAggregateEventCandidate(GeneratorSyntaxContext context)
    {
        if (context.Node is not TypeDeclarationSyntax declaration)
        {
            return null;
        }

        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol symbol || symbol.IsAbstract)
        {
            return null;
        }

        var aggregateTypes = SymbolHelpers.GetAggregateTypes(symbol);
        return aggregateTypes.Length == 0 ? null : new AggregateEventCandidate(symbol, aggregateTypes);
    }

    private static void EmitCoverageSource(SourceProductionContext context, ProjectionCandidate projection, IReadOnlyCollection<INamedTypeSymbol> aggregateEvents)
    {
        var builder = new StringBuilder();
        var namespaceName = projection.HostType.ContainingNamespace.IsGlobalNamespace
            ? null
            : projection.HostType.ContainingNamespace.ToDisplayString();

        builder.AppendLine("// <auto-generated />");

        if (namespaceName is not null)
        {
            builder.Append("namespace ").Append(namespaceName).AppendLine(";");
            builder.AppendLine();
        }

        builder.Append("internal static class ").Append(SymbolHelpers.GetMetadataClassName(projection.HostType)).AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    public static readonly global::System.Type[] Events =");
        builder.AppendLine("    {");

        foreach (var aggregateEvent in aggregateEvents.OrderBy(symbol => symbol.ToDisplayString()))
        {
            builder.Append("        typeof(")
                .Append(aggregateEvent.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .AppendLine("),");
        }

        builder.AppendLine("    };\n}");

        var hintName = projection.HostType.ToDisplayString().Replace('<', '_').Replace('>', '_').Replace('.', '_') + ".EventCoverage.g.cs";
        context.AddSource(hintName, SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private sealed class ProjectionCandidate(INamedTypeSymbol hostType, INamedTypeSymbol aggregateType)
    {
        public INamedTypeSymbol HostType { get; } = hostType;

        public INamedTypeSymbol AggregateType { get; } = aggregateType;
    }

    private sealed class AggregateEventCandidate(
        INamedTypeSymbol eventType,
        ImmutableArray<INamedTypeSymbol> aggregateTypes)
    {
        public INamedTypeSymbol EventType { get; } = eventType;

        public ImmutableArray<INamedTypeSymbol> AggregateTypes { get; } = aggregateTypes;
    }
}